/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import desenhos.Borracha;
import desenhos.Caneta;
import desenhos.Elipse;
import desenhos.Forma;
import desenhos.Linha;
import desenhos.Poligono;
import desenhos.Ponto;
import desenhos.Retangulo;
import desenhos.Texto;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import stack.ResizingArrayStack;

/**
 * @author Brenno Gaspar Pinto
 */
public class janelaPrincipal extends javax.swing.JFrame {
    
    // Atributos
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(janelaPrincipal.class.getName());
    
    private Forma novaForma;
    private int quantidadeLados;
    private String texto;
    private List<Ponto> caminho;
    private ResizingArrayStack pilha;
    private ResizingArrayStack pilhaRedo;
    private Forma emConstrucao = null;
    private float grossuraPincel;
    private boolean preencherB = false;
    
    /**
     * Creates new form janelaPrincipal
     */
    public janelaPrincipal() {
        initComponents();
        quantidadeLados = 3;
        pilha = new ResizingArrayStack();
        pilhaRedo = new ResizingArrayStack();
        painelDesenho.setPilha( pilha );
        painelDesenho.setFormaEmConstrucao( emConstrucao );
        
        configurarCtrlZ();
        configurarCtrlY();
    }

    // Função para a pilha undo (desfazer)
    private void undo (){
        if( !pilha.isEmpty() ) {
            Forma t = (Forma) pilha.pop();
            pilhaRedo.push( t );
            painelDesenho.repaint();
        }
    }
    
    // Função para a pilha redo (refazer)
    private void redo (){
        if( !pilhaRedo.isEmpty() ) {
            Forma t = (Forma) pilhaRedo.pop();
            pilha.push( t );
            painelDesenho.repaint();
        }
    }
    
    // Funções para configurar o CtrlZ e CtrlY na tela
    private void configurarCtrlZ() {
        KeyStroke ctrlZ = KeyStroke.getKeyStroke(KeyEvent.VK_Z, InputEvent.CTRL_DOWN_MASK); // combinar ctrl + z
        
        Action undoAction = new AbstractAction() {
            public void actionPerformed( ActionEvent e ) {
                undo();
            }
        };
        
        painelDesenho.getInputMap( JComponent.WHEN_IN_FOCUSED_WINDOW ).put( ctrlZ, "desfazer" );
        painelDesenho.getActionMap().put( "desfazer", undoAction );
    }
    
    private void configurarCtrlY() {
        KeyStroke ctrlY = KeyStroke.getKeyStroke( KeyEvent.VK_Y, InputEvent.CTRL_DOWN_MASK );
        
        Action redoAction = new AbstractAction() {
            public void actionPerformed( ActionEvent e ) {
                redo();
            }
        };
        
        painelDesenho.getInputMap( JComponent.WHEN_IN_FOCUSED_WINDOW ).put( ctrlY, "refazer" );
        painelDesenho.getActionMap().put( "refazer", redoAction );
    }
    
    private void criarPreview( java.awt.event.MouseEvent evt ) {
        if( btnBorracha.isSelected() || btnCaneta.isSelected() ) {
            int grossura = (int) painelDesenho.getGrossura();
            Forma preview = new Elipse();
            preview.setIniX( evt.getX() - (grossura / 2) );
            preview.setIniY( evt.getY() - (grossura / 2) );
            preview.setFimX( evt.getX() + (grossura / 2) );
            preview.setFimY( evt.getY() + (grossura / 2) );
            if( btnCaneta.isSelected() ) {
                preview.setCorPreenchimento( painelCorContorno.getBackground() );
            } else {
                preview.setCorPreenchimento( Color.WHITE );
            }            
            painelDesenho.setPreview( preview );
            painelDesenho.repaint();
        }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFerramentas = new javax.swing.ButtonGroup();
        painelDesenho = new ui.PainelDesenho();
        painelFerramentas = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnBorracha = new javax.swing.JToggleButton();
        btnLinha = new javax.swing.JToggleButton();
        btnCaneta = new javax.swing.JToggleButton();
        btnPoligono = new javax.swing.JToggleButton();
        btnRetangulo = new javax.swing.JToggleButton();
        btnElipse = new javax.swing.JToggleButton();
        painelCorPreenchimento = new javax.swing.JPanel();
        painelCorContorno = new javax.swing.JPanel();
        undo = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        preencher = new javax.swing.JCheckBox();
        btnTexto = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Paint");

        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseMoved(evt);
            }
        });
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        btnLimpar.setText("Limpar Tela");
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });

        btnGroupFerramentas.add(btnBorracha);
        btnBorracha.setText("Borracha");
        btnBorracha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBorracha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorracha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnLinha);
        btnLinha.setSelected(true);
        btnLinha.setText("Linha");
        btnLinha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLinha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnCaneta);
        btnCaneta.setText("Caneta");
        btnCaneta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCaneta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaneta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnPoligono);
        btnPoligono.setText("Poligono");
        btnPoligono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPoligono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPoligono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPoligono.addActionListener(this::btnPoligonoActionPerformed);

        btnGroupFerramentas.add(btnRetangulo);
        btnRetangulo.setText("Retangulo");
        btnRetangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRetangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnElipse);
        btnElipse.setText("Elipse");
        btnElipse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        painelCorPreenchimento.setBackground(new java.awt.Color(255, 255, 255));
        painelCorPreenchimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCorPreenchimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelCorPreenchimento.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorPreenchimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorPreenchimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorPreenchimentoLayout = new javax.swing.GroupLayout(painelCorPreenchimento);
        painelCorPreenchimento.setLayout(painelCorPreenchimentoLayout);
        painelCorPreenchimentoLayout.setHorizontalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelCorPreenchimentoLayout.setVerticalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelCorContorno.setBackground(new java.awt.Color(0, 0, 0));
        painelCorContorno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCorContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelCorContorno.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorContorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorContornoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorContornoLayout = new javax.swing.GroupLayout(painelCorContorno);
        painelCorContorno.setLayout(painelCorContornoLayout);
        painelCorContornoLayout.setHorizontalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelCorContornoLayout.setVerticalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        undo.setText("↩️");
        undo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undoMouseClicked(evt);
            }
        });

        redo.setText("↪️");
        redo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redoMouseClicked(evt);
            }
        });

        preencher.setText("Preencher");
        preencher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preencherMouseClicked(evt);
            }
        });

        btnGroupFerramentas.add(btnTexto);
        btnTexto.setText("Texto");
        btnTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTexto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTexto.addActionListener(this::btnTextoActionPerformed);

        javax.swing.GroupLayout painelFerramentasLayout = new javax.swing.GroupLayout(painelFerramentas);
        painelFerramentas.setLayout(painelFerramentasLayout);
        painelFerramentasLayout.setHorizontalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElipse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPoligono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCaneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorracha)
                .addGap(18, 18, 18)
                .addComponent(preencher)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addComponent(undo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelCorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFerramentasLayout.setVerticalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFerramentasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorracha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(undo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(preencher)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(painelCorContorno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
        if( btnLinha.isSelected() ) {
            novaForma = new Linha();
        } else if ( btnRetangulo.isSelected() ) {
            novaForma = new Retangulo();
        } else if ( btnElipse.isSelected() ) {
            novaForma = new Elipse();
        } else if ( btnPoligono.isSelected() ) {
            novaForma = new Poligono( quantidadeLados );
        } else if ( btnCaneta.isSelected() ) {
            novaForma = new Caneta();
            Ponto pontoInicial = new Ponto ( evt.getX(), evt.getY() );
            caminho = new ArrayList<>();
            caminho.add(pontoInicial);
            novaForma.setCaminho( caminho );
        } else if ( btnBorracha.isSelected() ) {
            novaForma = new Borracha();
            Ponto pontoInicial = new Ponto ( evt.getX(), evt.getY() );
            caminho = new ArrayList<>();
            caminho.add(pontoInicial);
            novaForma.setCaminho( caminho );
        } else if ( btnTexto.isSelected() ) {
            Ponto pontoInicial = new Ponto ( evt.getX(), evt.getY() );
            novaForma = new Texto( texto, pontoInicial );   
        }
        novaForma.setIniX( evt.getX() );
        novaForma.setIniY( evt.getY() );
        novaForma.setFimX( evt.getX() );
        novaForma.setFimY( evt.getY() );
        novaForma.setCorDoContorno( painelCorContorno.getBackground() );
        if( preencherB ) {
            novaForma.setCorPreenchimento( painelCorPreenchimento.getBackground() );
        } else {
            novaForma.setCorPreenchimento( null );
        }        
        grossuraPincel = painelDesenho.getGrossura();
        novaForma.setGrossura( grossuraPincel );
        emConstrucao = novaForma;
        painelDesenho.setFormaEmConstrucao( emConstrucao );
        painelDesenho.repaint();
        painelDesenho.setPreview( null );
    }//GEN-LAST:event_painelDesenhoMousePressed

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
        if( novaForma instanceof Caneta || novaForma instanceof Borracha ){
            Ponto pontoFinal = new Ponto( evt.getX(), evt.getY() );
            caminho.add(pontoFinal);
            novaForma.setCaminho(caminho);
        }
        novaForma.setFimX( evt.getX() );
        novaForma.setFimY( evt.getY() );
        pilha.push( novaForma );
        emConstrucao = null;
        painelDesenho.setFormaEmConstrucao( emConstrucao );
        painelDesenho.repaint();
    }//GEN-LAST:event_painelDesenhoMouseReleased

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        if( novaForma instanceof Caneta || novaForma instanceof Borracha ){
            Ponto pontoAtual = new Ponto( evt.getX(), evt.getY() );
            caminho.add(pontoAtual);
            novaForma.setCaminho(caminho);
        }
        novaForma.setFimX( evt.getX() );
        novaForma.setFimY( evt.getY() );
        painelDesenho.repaint();
    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void painelCorContornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorContornoMouseClicked
        Color corSelecionada = JColorChooser.showDialog( this, "Cor do Contorno", painelCorContorno.getBackground() );
        if( corSelecionada != null ) {
            painelCorContorno.setBackground( corSelecionada );
        }
    }//GEN-LAST:event_painelCorContornoMouseClicked

    private void painelCorPreenchimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorPreenchimentoMouseClicked
        Color corSelecionada = JColorChooser.showDialog( this, "Cor do Preenchimento", painelCorPreenchimento.getBackground() );
        if( corSelecionada != null ) {
            painelCorPreenchimento.setBackground( corSelecionada );
        }
    }//GEN-LAST:event_painelCorPreenchimentoMouseClicked

    private void btnPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonoActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de Lados: " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 3 ) {
                quantidadeLados = quantidade;
            } else {
                JOptionPane.showMessageDialog( this, "Por favor, insira um número maior que 2", "AVISO", JOptionPane.WARNING_MESSAGE );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( this, "Por favor, insira um número válido", "ERRO", JOptionPane.ERROR_MESSAGE );
        }        
    }//GEN-LAST:event_btnPoligonoActionPerformed

    private void undoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undoMouseClicked
        undo();
    }//GEN-LAST:event_undoMouseClicked

    private void redoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redoMouseClicked
        redo();
    }//GEN-LAST:event_redoMouseClicked

    private void preencherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preencherMouseClicked
        preencherB = !preencherB;
    }//GEN-LAST:event_preencherMouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        
        int resposta = JOptionPane.showConfirmDialog( 
            null, 
            "Deseja realmente limpar todos os desenhos do painel?\n\nEssa ação é irreversível!", 
            "Limpeza de painel", 
            JOptionPane.YES_NO_OPTION 
        );
        
        if( resposta == JOptionPane.YES_OPTION ) {
            pilha.clear();
            painelDesenho.repaint();
        }
        
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextoActionPerformed
        try{
            texto = JOptionPane.showInputDialog( "Frase que deseja escrever: " );
            if( texto.trim().isEmpty() ) {
                JOptionPane.showMessageDialog( this, "Digite algo para desenhar", "ERRO", JOptionPane.ERROR_MESSAGE );
            }
        } catch ( HeadlessException exc ) {
            JOptionPane.showMessageDialog( this, "Erro: " + exc, "ERRO", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnTextoActionPerformed

    private void painelDesenhoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseMoved
        criarPreview( evt );
    }//GEN-LAST:event_painelDesenhoMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new janelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBorracha;
    private javax.swing.JToggleButton btnCaneta;
    private javax.swing.JToggleButton btnElipse;
    private javax.swing.ButtonGroup btnGroupFerramentas;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnPoligono;
    private javax.swing.JToggleButton btnRetangulo;
    private javax.swing.JToggleButton btnTexto;
    private javax.swing.JPanel painelCorContorno;
    private javax.swing.JPanel painelCorPreenchimento;
    private ui.PainelDesenho painelDesenho;
    private javax.swing.JPanel painelFerramentas;
    private javax.swing.JCheckBox preencher;
    private javax.swing.JButton redo;
    private javax.swing.JButton undo;
    // End of variables declaration//GEN-END:variables
}
